# Generated by Django 4.2 on 2023-07-10 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 6, 31, 43, 601671, tzinfo=datetime.timezone.utc)),
        ),
    ]
