# Generated by Django 4.2 on 2023-07-10 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 8, 23, 24, 372254, tzinfo=datetime.timezone.utc)),
        ),
    ]
