# Generated by Django 4.2 on 2023-07-24 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_create_at_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 13, 5, 37, 919303, tzinfo=datetime.timezone.utc)),
        ),
    ]
