# Generated by Django 4.2 on 2023-07-25 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 5, 39, 25, 330567, tzinfo=datetime.timezone.utc)),
        ),
    ]
